### ISSUE TITLE
csharp-biscuits.annotationMinDistance not working as expected

### ISSUE THREAD

**Issue by hansWurst-creator** [code-biscuits/csharp-biscuits#1]
To me it looks like the min distance is not properly calculated I would expect that only the closing bracket after n number of lines would be marked. Here annotations are added after n number of lines.

csharp-biscuits.annotationMinDistance set to 52
![image](https://user-images.githubusercontent.com/70693364/96577504-00293780-12d4-11eb-8f56-420b188606a0.png)

csharp-biscuits.annotationMinDistance set to 5 
![image](https://user-images.githubusercontent.com/70693364/96577369-d112c600-12d3-11eb-8ba2-93ac6544cd64.png)

**Comment by cmgriffing** [comment]
Thanks. Its not quite what you think is happening. It does need to be fixed though. So thanks for pointing it out.

Current explanation for what is actually happening:

Right now, every chained function is identified as being part of the same block. The annotation just prints the first line of said block.

So it is taking the distance into account properly, but it is not identifying that the inner chained functions should not be individually annotated.

**Comment by cmgriffing** [comment]
Thanks again for reporting this. We have it fixed for CSharp inside of Assorted Biscuits and will be deprecating this extension.
